### ISSUE TITLE
Suggestion/Bug: Placed rows do not respect player rotation.

### ISSUE THREAD

**Issue by GentlemanCheesy** [infernalstudios/BetterBridging#3]
Placed rows do not respect the orientation of the player, if placed facing specific directions, it will not change the placement to respect this. Tested on 1.20.1 Neoforge
![image](https://github.com/infernalstudios/BetterBridging/assets/68432025/7b72845b-0c09-419d-bb1b-d7dd667ad7da)

**Comment by tinytransfem** [comment]
This is not a bug, you rotate the row using the assigned hotkey, R by default
