### ISSUE TITLE
Bug: Directional Blocks cannot be placed against certain faces.

### ISSUE THREAD

**Issue by GentlemanCheesy** [infernalstudios/BetterBridging#4]
Rows will not be placed correctly when placed on any face other than the bottom and top of blocks. Tested on Neoforge 1.20.1.
![image](https://github.com/infernalstudios/BetterBridging/assets/68432025/cae86c14-723b-445c-a36a-076583f11274)
![image](https://github.com/infernalstudios/BetterBridging/assets/68432025/bc346a5c-2f89-43ad-a8eb-81026f92941c)

**Comment by GentlemanCheesy** [comment]
Just figured out its something to do with the directional properties of the logs, regular blocks work fine.

**Comment by tinytransfem** [comment]
Not sure why this is happening but I have an idea how to fix this, I'll hopefully have a fix up tomorrow

**Comment by tinytransfem** [comment]
This is fixed in version 1.0.1, now available on both Curseforge and Modrinth, thank you for notifying us of this issue!
