### ISSUE TITLE
Server Side Crashes

### ISSUE THREAD

**Issue by GentlemanCheesy** [infernalstudios/BetterBridging#5]
Adding this mod to my pack crashed on server side. Singleplayer works as intended.

Tested on Neoforge 1.20.1

Crash report:
https://pastebin.com/DSmjBtpK

**Comment by tinytransfem** [comment]
This is strange because it loads fine on the server on my end but it's an easy fix, update will be out soon!

**Comment by GentlemanCheesy** [comment]
Thank you very much!

**Comment by tinytransfem** [comment]
This is fixed in version 1.0.2, now available on Curseforge and Modrinth, the update is needed for both 1.20.1 and 1.19.4. Thank you for reporting this!
